from __future__ import annotations

import argparse
from dataclasses import dataclass, field
from pathlib import Path

import yaml

from app.core.config import get_settings


@dataclass(slots=True)
class ScaffoldedAppSpec:
    package_name: str
    display_name: str
    description: str
    service_name: str | None = None
    kind: str = "sibling_app"
    icon: str = "IconAppWindow"
    order: int = 100
    powered_by: str = "Atlas Haven"
    ui_location: str = "bridge"
    image: str = "ghcr.io/atlas-haven/sample-app:latest"
    host_port: int = 8099
    container_port: int = 8080
    docs_slug: str | None = None
    dependency_ids: list[str] = field(default_factory=list)
    storage_requires: list[str] = field(default_factory=list)
    include_hook_stub: bool = False

    def resolved_service_name(self) -> str:
        if self.service_name:
            return self.service_name
        normalized = self.package_name.replace("-", "_")
        if not normalized.startswith("nomad_"):
            normalized = f"nomad_{normalized}"
        return normalized

    def resolved_docs_slug(self) -> str:
        return self.docs_slug or f"app-{self.package_name.replace('_', '-')}"


class AppScaffolder:
    def __init__(self, workspace_root: Path | None = None) -> None:
        settings = get_settings()
        self.workspace_root = workspace_root or settings.workspace_root

    def scaffold(self, spec: ScaffoldedAppSpec, *, force: bool = False) -> Path:
        apps_root = self.workspace_root / "apps"
        target_dir = apps_root / spec.package_name
        if target_dir.exists() and not force:
            raise FileExistsError(f"App package already exists: {target_dir}")

        target_dir.mkdir(parents=True, exist_ok=True)
        manifest = yaml.safe_dump(self._build_manifest(spec), sort_keys=False)
        self._write_file(target_dir / "app.yaml", manifest)
        self._write_file(
            target_dir / "docs" / "overview.md",
            self._build_docs_overview(spec),
        )
        self._write_file(
            target_dir / "tests" / "test_smoke.py",
            self._build_smoke_test(spec),
        )
        if spec.include_hook_stub:
            self._write_file(target_dir / "hooks.py", self._build_hook_stub(spec))

        return target_dir

    def _build_manifest(self, spec: ScaffoldedAppSpec) -> dict[str, object]:
        service_name = spec.resolved_service_name()
        return {
            "id": service_name,
            "kind": spec.kind,
            "display": {
                "name": spec.display_name,
                "description": spec.description,
                "icon": spec.icon,
                "powered_by": spec.powered_by,
                "order": spec.order,
                "ui_location": spec.ui_location,
            },
            "runtime": {
                "image": spec.image,
                "command": ["sh", "-c", "sleep infinity"],
                "ports": [
                    {
                        "host": spec.host_port,
                        "container": spec.container_port,
                    }
                ],
                "restart": "unless-stopped",
            },
            "network": {"join": "project-nomad_default"},
            "storage": {"requires": spec.storage_requires},
            "dependencies": spec.dependency_ids,
            "healthcheck": {
                "type": "http",
                "target": f"http://{{container_name}}:{spec.container_port}",
            },
            "hooks": {},
            "updates": {"strategy": "image_tag"},
            "permissions": {"docker_socket": False},
            "capabilities": {"internet_required_for_install": False},
            "docs": {"slug": spec.resolved_docs_slug()},
            "tests": {"smoke": f"apps/{spec.package_name}/tests/test_smoke.py"},
        }

    def _build_docs_overview(self, spec: ScaffoldedAppSpec) -> str:
        return (
            f"# {spec.display_name}\n\n"
            "## Status\n\n"
            "Planned\n\n"
            "## Purpose\n\n"
            f"{spec.description}\n\n"
            "## Notes\n\n"
            "- Generated by the Atlas Haven app scaffolder.\n"
            "- Replace this overview with app-specific operator guidance.\n"
        )

    def _build_smoke_test(self, spec: ScaffoldedAppSpec) -> str:
        return (
            "from pathlib import Path\n\n\n"
            "def test_sample_app_package_is_scaffolded() -> None:\n"
            "    assert (Path(__file__).resolve().parents[1] / 'app.yaml').exists()\n"
        )

    def _build_hook_stub(self, spec: ScaffoldedAppSpec) -> str:
        return (
            "from pathlib import Path\n\n\n"
            "def preflight() -> None:\n"
            "    return None\n\n\n"
            "def preinstall(target_dir: str | Path | None = None) -> None:\n"
            "    return None\n\n\n"
            "def postinstall() -> None:\n"
            "    return None\n\n\n"
            "def prestart() -> None:\n"
            "    return None\n\n\n"
            "def poststart() -> None:\n"
            "    return None\n\n\n"
            "def preupdate() -> None:\n"
            "    return None\n\n\n"
            "def rollback() -> None:\n"
            "    return None\n\n\n"
            "def preuninstall() -> None:\n"
            "    return None\n\n\n"
            "def postuninstall() -> None:\n"
            "    return None\n"
        )

    def _write_file(self, path: Path, content: str) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)


def scaffold_app(spec: ScaffoldedAppSpec, *, force: bool = False) -> Path:
    return AppScaffolder().scaffold(spec, force=force)


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Scaffold a new Atlas Haven app package")
    parser.add_argument("package_name")
    parser.add_argument("display_name")
    parser.add_argument("description")
    parser.add_argument("--service-name")
    parser.add_argument("--kind", default="sibling_app")
    parser.add_argument("--icon", default="IconAppWindow")
    parser.add_argument("--order", type=int, default=100)
    parser.add_argument("--powered-by", default="Atlas Haven")
    parser.add_argument("--ui-location", default="bridge")
    parser.add_argument("--image", default="ghcr.io/atlas-haven/sample-app:latest")
    parser.add_argument("--host-port", type=int, default=8099)
    parser.add_argument("--container-port", type=int, default=8080)
    parser.add_argument("--docs-slug")
    parser.add_argument("--dependency", action="append", default=[])
    parser.add_argument("--storage-requires", action="append", default=[])
    parser.add_argument("--hook-stub", action="store_true")
    parser.add_argument("--force", action="store_true")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_arg_parser()
    args = parser.parse_args(argv)
    scaffold_app(
        ScaffoldedAppSpec(
            package_name=args.package_name,
            display_name=args.display_name,
            description=args.description,
            service_name=args.service_name,
            kind=args.kind,
            icon=args.icon,
            order=args.order,
            powered_by=args.powered_by,
            ui_location=args.ui_location,
            image=args.image,
            host_port=args.host_port,
            container_port=args.container_port,
            docs_slug=args.docs_slug,
            dependency_ids=list(args.dependency),
            storage_requires=list(args.storage_requires),
            include_hook_stub=args.hook_stub,
        ),
        force=args.force,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
